#!/bin/bash 
#SBATCH --nodes=1                        # requests 3 compute servers
#SBATCH --cpus-per-task=4                # uses 1 compute core per task
#SBATCH --time=4:00:00
#SBATCH --mem=8GB
#SBATCH --job-name=outlet-svm
#SBATCH --output=outlet-model/slurm.out

module purge
module load r/gcc/4.2.0
Rscript outlet-model/svm.R

